export const SELECT_ITEM_FOR_UPGRADE = "SELECT_ITEM_FOR_UPGRADE";
export const SELECT_SCROLL_FOR_UPGRADE = "SELECT_SCROLL_FOR_UPGRADE";
export const SET_ITEMS = "SET_ITEMS";
export const SET_COLLECTIBLE_NFTs = "SET_COLLECTIBLE_NFTs";
